= Changelog

== 0.13.0

This update fixes an issue with `desired_count` for services without autoscaling.

=== Breaking Changes

You will need to add a `moved` block to your configuration to avoid recreating your service.

If you are using `desired_count`, add the following next to your module block:

[source, hcl]
----
moved = {
  from = module.ecs_service.aws_ecs_service.service
  from = module.ecs_service.aws_ecs_service.service[0]
}
----

If you are using `autoscaling`, add the following next to your module block:

[source, hcl]
----
moved = {
  from = module.ecs_service.aws_ecs_service.service
  from = module.ecs_service.aws_ecs_service.service_with_autoscaling[0]
}
----

This block can be deleted after apply.

== 0.12.0
* Add variable for enabling `aws ecs exec` from AWS CLI.
* Rename `name_prefix` to `application_name`.

=== Breaking Changes
* Rename `name_prefix` to `application_name`.

== 0.8.0

=== Breaking Changes

* Require `terraform >= v1.3.0`
* Changed `lb_listener.path_parameter` to `lb_listener.conditions`.

To update, chang your configuration from:

[source,terraform]
----
lb_listeners = [{
  listener_arn      = data.aws_lb_listener.http.arn
  security_group_id = one(data.aws_lb.main.security_groups)
  path_pattern = "/${local.application_name}/*"
}]
----

To this:

[source, terraform]
----
lb_listeners = [{
  listener_arn      = data.aws_lb_listener.http.arn
  security_group_id = one(data.aws_lb.main.security_groups)
  conditions = [{
    path_pattern = "/${local.application_name}/*"
  }]
}]
----

== New Features

* Add ability to have multiple conditions for your load balancer listeners.
* Add ability to use `host_header` as a lb listener condition
