version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

# Preferably these would be a CircleCI parameter,
# but parameters doesn't support lists or maps :(
terraform-versions: &terraform-versions
  - 1.4.4

example-folders: &example-folders
  - examples/simple
  - examples/on-prem
  - examples/autoscaling
  - examples/autoscaling-with-custom-metrics

workflows:
  validate:
    jobs:
      - terraform/validate:
          name: Validate Module
          checkout: true
          path: .
          matrix:
            parameters:
              tag: *terraform-versions
      - terraform/validate:
          name: Validate Examples
          checkout: true
          matrix:
            parameters:
              tag: *terraform-versions
              path: *example-folders
