name: Validate Terraform

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  validate-module: # Required status checks in GitHub
    uses: nsbno/platform-actions/.github/workflows/lint.terraform.yml@v2
    with:
      working-directory: .
      terraform-version: "1.14.8"

  validate-examples:
    strategy:
      matrix:
        working_directory:
          - examples/simple # Part of the required status checks in GitHub
          - examples/on-prem
          - examples/datadog
          - examples/autoscaling
          - examples/autoscaling-predictive
          - examples/autoscaling-with-custom-metrics
          - examples/blue-green-deployment
    uses: nsbno/platform-actions/.github/workflows/lint.terraform.yml@v2
    with:
      working-directory: ${{ matrix.working_directory }}
      terraform-version: "1.14.8"
      run-fmt: false # terraform fmt from validate-module already covers the examples too
